#!/usr/bin/env sh
# Fails unless all three clients are generated by the same, exactly pinned orval.
#
# One document, three clients: if the generators differ then the outputs differ,
# and no per-app check can see it — each app's generated code is consistent with
# its own generator, so each app's drift check passes. That is how desktop came
# to carry generated code its own lockfile could not reproduce, and how one
# client ended up with a `$exactMatch` parameter the other two had never heard
# of. Parity is only visible from above, so it is asserted here.
#
# Exact versions, not ranges. `^8.34.0` is what quietly resolved web and desktop
# to 8.37.0 while mobile's lockfile stayed on 8.34.0 — a caret on a code
# generator is a promise that the output may change without anyone asking.
set -eu

cd "$(dirname "$0")/../.."

apps="web desktop mobile"
status=0
declared=""

# The declared pin. The `[0-9^~]` class is what skips desktop's `"orval": "orval"`
# script entry, which is a command and not a version.
for app in $apps; do
    spec=$(grep -o '"orval": "[0-9^~][^"]*"' "$app/package.json" | sed 's/.*: "//; s/"$//' || true)
    if [ -z "$spec" ]; then
        echo "$app: no orval devDependency found in package.json" >&2
        status=1
        continue
    fi
    case "$spec" in
        *[\^~x\*]* | *' - '* | '')
            echo "$app: orval is pinned as '$spec' — a range, not a version." >&2
            echo "$app: pin it exactly, or the three clients drift apart again." >&2
            status=1
            ;;
    esac
    echo "$app declares $spec"
    declared="$declared$spec
"
done

if [ "$(printf '%s' "$declared" | sort -u | grep -c .)" -ne 1 ]; then
    echo "The three package.json files do not ask for the same orval." >&2
    status=1
fi

# The resolved version, which is what actually runs.
resolved=""
for app in $apps; do
    v=$(grep -o 'orval@[0-9][0-9.]*' "$app/pnpm-lock.yaml" | sort -u | tr '\n' ' ' | sed 's/ $//')
    echo "$app resolves $v"
    resolved="$resolved$v
"
done

if [ "$(printf '%s' "$resolved" | sort -u | grep -c .)" -ne 1 ]; then
    {
        echo
        echo "The three clients are not generated by the same orval."
        echo "One contract generated by three generators is three different"
        echo "clients. Align them, reinstall, and run 'just gen'."
    } >&2
    status=1
fi

exit "$status"
