-- A repository can be connected before anything has looked at it.
--
-- Saving one is saving a URL: it belongs to no host, and every host that runs a
-- session for it clones with the same provider token. Requiring a live worker
-- to write the row meant a laptop with nothing connected could not record a URL
-- it already had permission to use.
--
-- NULL means nobody has read the remote yet. The trunk is whatever that
-- repository says it is, and the first session to clone it finds out and fills
-- this in. A placeholder would be a guess, and guessing `main` at a repository
-- whose trunk is called something else is the mistake this column exists to
-- prevent.
ALTER TABLE repos ALTER COLUMN default_branch DROP NOT NULL;
