-- The value an agent authenticates with, whichever mode it's in: a long-lived
-- token from `claude setup-token`, or a metered API key.
--
-- In the database rather than the keychain because a keychain doesn't exist on
-- a server, and every worker has to be able to get at this. Stored as given for
-- now — encrypting it is the next piece of work, and the column doesn't change
-- when that lands.
--
-- Which environment variable carries it is derived from the agent and mode at
-- the moment a workspace starts, not recorded here. That's a delivery detail
-- and it shouldn't be frozen into a row.
ALTER TABLE agents ADD COLUMN secret TEXT;
